# Generated by Django 3.1.3 on 2020-11-28 17:17

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csvdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('details', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='fonts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('path', models.CharField(max_length=10000, unique=True)),
                ('fpath', models.CharField(max_length=10000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='saveimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(default='images/default.png', max_length=255, upload_to='images')),
            ],
        ),
    ]
