# Generated by Django 3.1.3 on 2020-11-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_saveimage_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='fonts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, unique=True)),
                ('path', models.CharField(max_length=10000, unique=True)),
            ],
        ),
    ]
